// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507151525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CaracteristicaComputadora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IdEquipo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_equipo");

                    b.Property<string>("Procesador")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("procesador");

                    b.Property<string>("Ram")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ram");

                    b.Property<string>("Rom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("rom");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipo");

                    b.ToTable("caracteristicas_computadora", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ControlActivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Custodio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("custodio");

                    b.Property<string>("DetallesAuditoria")
                        .HasColumnType("text")
                        .HasColumnName("detalles_auditoria");

                    b.Property<DateTime?>("FechaAuditoria")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_auditoria");

                    b.Property<string>("IdEquipo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_equipo");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipo");

                    b.ToTable("control_activos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Custodio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cargo");

                    b.Property<string>("Cedula")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cedula");

                    b.Property<long?>("IdDepartamento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_departamento");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .HasDatabaseName("IX_Custodio_Cedula");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Custodios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Departamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GestionActivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_devolucion");

                    b.Property<long?>("IdCustodio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_custodio");

                    b.Property<string>("IdEquipo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_equipo");

                    b.HasKey("Id");

                    b.HasIndex("IdCustodio");

                    b.HasIndex("IdEquipo");

                    b.ToTable("gestion_activos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Hardware", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoCne")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("codigo_cne");

                    b.Property<string>("Estado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_adquisicion");

                    b.Property<string>("IdEquipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_equipo");

                    b.Property<long?>("IdSuministro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_suministro");

                    b.Property<string>("Marca")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("modelo");

                    b.Property<string>("NombreDispositivo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre_dispositivo");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ubicacion");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Hardware_Estado");

                    b.HasIndex("IdEquipo")
                        .HasDatabaseName("IX_Hardware_IdEquipo");

                    b.ToTable("gestion_hardware", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HistorialCustodio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Custodio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("custodio");

                    b.Property<long?>("IdDepartamento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_departamento");

                    b.Property<DateTime?>("TimestampEvento")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp_evento");

                    b.HasKey("Id");

                    b.ToTable("historial_custodios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Kit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("CANTIDAD");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Insumo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("INSUMO");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("OBSERVACION");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Serie");

                    b.HasKey("Id");

                    b.ToTable("Kits", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cargo");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cedula");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("TempPass")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tempPass");

                    b.HasKey("Id");

                    b.ToTable("Personal", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Suministro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FechaRetiro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_retiro");

                    b.Property<string>("IdEquipo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_equipo");

                    b.Property<string>("IdEquipoAsignado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_equipoAsignado");

                    b.Property<string>("TipoSuministro")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tipo_suministro");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipo");

                    b.ToTable("suministros_remanufacturados", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cargo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Pass");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Usuario_Email");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuario_Nombre");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CaracteristicaComputadora", b =>
                {
                    b.HasOne("Domain.Entities.Hardware", "Hardware")
                        .WithMany("Caracteristicas")
                        .HasForeignKey("IdEquipo")
                        .HasPrincipalKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Domain.Entities.ControlActivo", b =>
                {
                    b.HasOne("Domain.Entities.Hardware", "Hardware")
                        .WithMany("ControlesActivos")
                        .HasForeignKey("IdEquipo")
                        .HasPrincipalKey("IdEquipo");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Domain.Entities.Custodio", b =>
                {
                    b.HasOne("Domain.Entities.Departamento", "Departamento")
                        .WithMany("Custodios")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Domain.Entities.GestionActivo", b =>
                {
                    b.HasOne("Domain.Entities.Custodio", "Custodio")
                        .WithMany("GestionActivos")
                        .HasForeignKey("IdCustodio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Hardware", "Hardware")
                        .WithMany("GestionActivos")
                        .HasForeignKey("IdEquipo")
                        .HasPrincipalKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Custodio");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Domain.Entities.Suministro", b =>
                {
                    b.HasOne("Domain.Entities.Hardware", "Hardware")
                        .WithMany("Suministros")
                        .HasForeignKey("IdEquipo")
                        .HasPrincipalKey("IdEquipo");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Domain.Entities.Custodio", b =>
                {
                    b.Navigation("GestionActivos");
                });

            modelBuilder.Entity("Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Custodios");
                });

            modelBuilder.Entity("Domain.Entities.Hardware", b =>
                {
                    b.Navigation("Caracteristicas");

                    b.Navigation("ControlesActivos");

                    b.Navigation("GestionActivos");

                    b.Navigation("Suministros");
                });
#pragma warning restore 612, 618
        }
    }
}
